### ISSUE TITLE
Place version/revision number somewhere visible.

### ISSUE THREAD

**Issue by BreadMaker** [rmcauley/rainwave#102]
Useful for nerds and to make people realize the long walk behind this project.

Please, make this happen.

**Comment by rmcauley** [comment]
I've removed the About screen entirely right now for Rainwave 5 - but I am genuinely curious why you'd say it's useful!

At the risk of being dismissive, I'd say it's not useful because the difference between Rainwave website versions is pretty large and fairly apparent based just on the look and feel of the site. (admittedly the difference between 4 and 5 is less dramatic than 2->3->4 was)  If we're looking for API differences, the API is remaining backwards compatible - I may add new commands or add more data to existing ones, but I'm not changing anything current.  For translators, the locale pages exist ( http://rainwave.cc/locale/ ) so they can see which lines are missing, regardless of version. (5 uses the same library and lines as 4 with some additions/changes)

If you really want to know the exact revision number (which is not necessarily the same as version number, as small hotfixes bump the revision) you can just view the source of the front page, search for "/static/baked/" and look at the revision number there.  As of this writing it is revision 97.

**Comment by BreadMaker** [comment]
My point is, it's important to show to non tech-savvy or no-code-digging people, the amount of work there's in this project, that's all. "Please understand".

**Comment by rmcauley** [comment]
I am honestly not really getting the point though - how does this information benefit anyone?

Again I'm not trying to be dismissive, I just... really don't understand.

**Comment by BreadMaker** [comment]
Perhaps we are facing a cultural difference here. Perhaps, we should not make a big deal of it. Perhaps we should move on. 

Let me tell you a story. 

Once upon a time, there was a machine, badly wrapped in a box, with small switches on the front and a bright red button on top. Once you press it, the most amazing thing in the universe happens. People around the world gathered in awe to see how the machine does its thing. Even, some people choose to translate the labels of the switches. The next version was made with more love and dedication than its predecessor. Even came with a sticker on the side with the name, thanks to those who translated, and also with some technical information and references. Many more iterations followed, each more brilliant than the last. But one day, when it came the shiny new version, there was something wrong. On the side, there was only a logo, nothing more. Few people noticed the change, for them, something was lost that day.

**Comment by rmcauley** [comment]
Version/revision number is very different from an about page or a credits/staff page. :)  The latter is something more easily understood as a loss of value, both in ability to recognize the volume of work, and in the ability to be recognized for the volume of work.
