### ISSUE TITLE
[Windows] inotify not available

### ISSUE THREAD

**Issue by ClosedEyesSeeing** [rmcauley/rainwave#144]
It seems like inotify is not available for Windows which causes the rw_scanner to fail on a Windows host. Currently looking for an alternative to run the scanner with with minimal changes.

**Comment by rmcauley** [comment]
`inotify` is a Linux only library, yeah. :(

We used to use `watchdog`, you can see the last version where we used it here: https://github.com/rmcauley/rainwave/blob/0fcaee4029c7690a617b6877804c3f3471e64b7a/backend/filemonitor.py

We switched to `inotify` because we were having numerous crash, deadlock, and race issues because of the Watchdog threading works.  Rather than try to continue wrestling with Watchdog, we moved to the Linux-only `inotify` as rainwave.cc runs on Debian.  We didn't think we had anyone else using Rainwave, let alone on Windows! :(  Sorry. 🙇 

If you're just looking to develop, or to run the site as a hobby, you can check out the `filemonitor.py` used in the commit above and the app will run.

I can't make any guarantees as to the scanner working in the background as it should on Windows at that point though, we've never run a production Rainwave on Windows.  I've only used Windows for developing Rainwave, and recently switched to using a Linux VM to mimic the production rainwave.cc.

If you have any questions or suggestions, let me know. :)

**Comment by ClosedEyesSeeing** [comment]
That's perfect! Thanks for such a quick reply. I'll give that watchdog a try and see what happens - I suppose I should have used the native linux, but I figured Windows would be a fun challenge. :) 

Thanks again!

**Comment by rmcauley** [comment]
If you have any further questions, stop by our Discord or post issues here. :)  If you're trying to get a Rainwave instance setup I'll do what I can to help!
