### ISSUE TITLE
Project does not conform to PEP8

### ISSUE THREAD

**Issue by williamjacksn** [rmcauley/rainwave#85]
I am opening this issue to find out if you would welcome pull requests that changed the Python coding style to conform to PEP8.

Mostly this will standardize indentation, blank lines, and other whitespace.

I assume that your editor is configured in such a way that it does not complain about these things.

**Comment by rmcauley** [comment]
Off the top of my head, here's what I can think for PEP8 violations in Rainwave:

1. Tabs not spaces (although not required by PEP8 I admit it's not standard)
2. Completely ignoring 79 character limit
3. Multi-line strings in some places use backslashes to continue strings rather than using line expansion (" " \n " ")
4. We have single blank lines between classes
5. Wildcard imports for API requests (intentional design decision)
6. Some inline comments
7. No docstrings
8. No versioning
9. Some mixed variable naming standards re: underscores (e.g. tuned_in vs tunedin)
10. Not using explicit exception raising
11. Some use of raise Exception "hello" rather than raise Exception("hello")

Comments:
1. tabs v spaces: Indifferent but would like to/have to change Javascript side in R5 branch to the same standard.
2. character limits: Agree with 99-per-line limit, disagree with 79.
3. multi-line strings: Agree with PEP.
4. double lines between classes: Indifferent.
5. wildcard imports: Agree with PEP but is necessary for RW.
6. inline comments: Agree with PEP.
7. docstrings: Agree with PEP but am lazy bum.
8. versioning: Agree with PEP but don't see the value in it for RW.
9. variable naming: Agree with PEP but would like consistent naming between Python and JS.
10. explicit exception raising: Agree with PEP.
11. syntax on exception raising: Agree with PEP.

Any other issues regarding PEP you see with Rainwave?

**Comment by williamjacksn** [comment]
You covered the bulk of it. A few other small things I see are:

1. Whitespace after `[` and before `]` in list literals.
2. Whitespace after `{` and before `}` in dict literals.
3. Spaces around `=` in default function parameters.

Are you only doing JS dev on the r5 branch? Should I just send all style changes straight to that branch instead of to master?

**Comment by rmcauley** [comment]
Python changes should happen in master, as that's (99.9%) unchanged in the R5 branch.  All JS is currently happening in R5.

I think there are better ways to spend time on Rainwave, but if it's really bugging you or you have some auto-magic PEP8er go for it. :)

**Comment by williamjacksn** [comment]
I opened this issue because I wanted to contribute but didn't really know how. If you can give me some ideas of things you need help with I can forget about this PEP8 busy-work.

**Comment by rmcauley** [comment]
I sure can!  I'll take it out of this ticket though.
